language: php

php:
    - 7.0
    - 7.1
    - 7.2
    - nightly

sudo: false

matrix:
    fast_finish: true
    allow_failures:
        - php: nightly

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer require --no-update satooshi/php-coveralls:^1.0
  - travis_retry composer install --no-interaction --prefer-source

before_script:
  - mkdir -p build/logs

script:
  - ./vendor/bin/parallel-lint src test
  - ./vendor/bin/phpunit --verbose --coverage-clover build/logs/clover.xml
  - ./vendor/bin/phpcs src --standard=psr2 -sp
  - ./vendor/bin/phpstan analyse -l 3 -c phpstan.neon src test

after_success:
  - travis_retry php vendor/bin/coveralls
